FROM        ubuntu:14.04
MAINTAINER Flavio Souza <flavioluiz.ssouza@gmail.com>
RUN         apt-get update && apt-get install -y redis-server
VOLUME /data
WORKDIR /data
EXPOSE      6379
ENTRYPOINT  ["/usr/bin/redis-server"]